# Generated by Django 5.0.3 on 2024-12-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reciept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('cooking_steps', models.TextField()),
                ('cooking_time', models.DateTimeField()),
                ('image', models.ImageField(upload_to='image_from_client/')),
                ('author', models.CharField(max_length=50)),
            ],
        ),
    ]
