# Generated by Django 5.0.3 on 2024-12-24 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_reciept'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reciept',
            new_name='Receipt',
        ),
    ]
