# Generated by Django 5.0.3 on 2024-12-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_reciept_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='cooking_time',
            field=models.DateTimeField(null=True),
        ),
    ]
