# Generated by Django 5.0.3 on 2024-12-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_receipt_cooking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='cooking_steps',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='cooking_time',
            field=models.TimeField(),
        ),
    ]
