# Generated by Django 5.0.3 on 2024-12-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_receipt_cooking_steps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='cooking_steps',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='cooking_time',
            field=models.TimeField(default=None),
        ),
    ]
