# Generated by Django 5.0.3 on 2024-12-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_receipt_cooking_steps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='cooking_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='image',
            field=models.ImageField(upload_to='static/img/'),
        ),
    ]
