# Generated by Django 5.0.3 on 2024-12-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_receipt_cooking_time_alter_receipt_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='main/static/img/'),
        ),
    ]
