# Generated by Django 5.0.3 on 2025-01-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_receipt_user_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
    ]
