# Generated by Django 5.0.3 on 2025-01-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_receipt_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='author',
            field=models.CharField(max_length=50, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='cooking_steps',
            field=models.TextField(verbose_name='Шаги приготовления'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='cooking_time',
            field=models.TimeField(null=True, verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='main/static/img/', verbose_name='Изображение'),
        ),
    ]
